version: '3.8'

services:
  website:
    image: sidneyjunior26/dotnet-website:latest
    container_name: app_container
    ports:
      - "8080:80" # ajuste as portas conforme necessário
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
