global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 3s

# Local Prometheus collector for testing and dashboard development purposes.

scrape_configs:
  - job_name: web-metrics
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["docker.for.mac.localhost:8080"]

  - job_name: prometheus-net
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.localhost:9090"]
